### ISSUE TITLE
CSS Colors

### ISSUE THREAD

**Issue by rxb3rth** [rxb3rth/color-palette#2]
Allow user to choose what kind of color to copy (RGB, HEX, HSL, RGBA, HSLA)

**Comment by William-Schutte** [comment]
Hey, I'd like to help. How would you like this implemented? A row of buttons along the top of the page maybe?

**Comment by rxb3rth** [comment]
> Hey, I'd like to help. How would you like this implemented? A row of buttons along the top of the page maybe?

Hey, sure!

I think it would be better to have a selector in the informative part of the page like this:

![image](https://user-images.githubusercontent.com/30651910/95657315-2f8db680-0b14-11eb-82d1-cbc03b7c7b8c.png)

**Comment by William-Schutte** [comment]
Ok, I've got something like this so far and will work on the algorithms for transforming the values after lunch!
![Screen Shot 2020-10-10 at 12 05 48 PM](https://user-images.githubusercontent.com/59342351/95659735-1de6e780-0af1-11eb-918a-8888ebb5f4ff.png)

**Comment by rxb3rth** [comment]
> Ok, I've got something like this so far and will work on the algorithms for transforming the values after lunch!
> ![Screen Shot 2020-10-10 at 12 05 48 PM](https://user-images.githubusercontent.com/59342351/95659735-1de6e780-0af1-11eb-918a-8888ebb5f4ff.png)

Looks great, good job! 💯

**Comment by rxb3rth** [comment]
@all-contributors please add @rxb3rth for code

**Comment by rxb3rth** [comment]
@all-contributors please add @William-Schutte for code
