### ISSUE TITLE
Fix the Footer Menu Styling

### ISSUE THREAD

**Issue by chinmaym07** [rxb3rth/color-palette#8]
Issue :  On clicking the Color Item in color list , FooterMenu open up from the bottom, It's content is not properly aligned.

https://user-images.githubusercontent.com/44670961/136835693-1dab0279-f959-461d-9b0b-96eae4a98b13.mp4

**Comment by chinmaym07** [comment]
Shall I fix this @rxb3rth  ?

**Comment by rxb3rth** [comment]
> Shall I fix this @rxb3rth  ?

If you want and have time
